// Copyright 2022-2025 Ilya Zverev
// This file is a part of Every Door, distributed under GPL v3 or later version.
// Refer to LICENSE file and https://www.gnu.org/licenses/gpl-3.0.html for details.
const kCommonKeys = <String>{
  'building', 'source', 'highway', 'addr:housenumber', 'addr:street',
  'addr:city', 'name', 'addr:postcode', 'natural', 'surface', 'landuse',
  'addr:country', 'power', 'building:levels', 'waterway', 'amenity',
  'service', 'oneway', 'barrier', 'height', 'access', 'ref', 'start_date',
  'addr:state', 'maxspeed', 'lanes', 'wall', 'ref:bag', 'layer', 'type',
  'addr:place', 'tracktype', 'operator', 'ele', 'place', 'leisure', 'lit',
  'addr:suburb', 'created_by', 'bicycle', 'railway', 'foot', 'crossing',
  'addr:province', 'bridge', 'name:en', 'addr:district', 'man_made', 'shop',
  'roof:shape', 'leaf_type', 'footway', 'attribution',
  'nysgissam:nysaddresspointid', 'intermittent', 'addr:city:simc',
  'public_transport', 'ref:bygningsnr', 'addr:conscriptionnumber',
  'ref:ruian:building', 'tunnel', 'note', 'water', 'building:ruian:type',
  'import', 'leaf_cycle', 'entrance', 'bus', 'lacounty:bld_id',
  'lacounty:ain', 'addr:municipality', 'building:units', 'tourism',
  'smoothness', 'sidewalk', 'source_ref', 'osak:identifier', 'website',
  'addr:province:en', 'addr:district:en', 'width', 'opening_hours',
  'wikidata', 'ref:ruian:addr', 'addr:subdistrict', 'addr:interpolation',
  'gauge', 'material', 'sport', 'network', 'description', 'voltage',
  'addr:street:en', 'wheelchair', 'building:part', 'boundary',
  'building:flats', 'parking', 'roof:levels', 'phone', 'ref:linz:address_id',
  'addr:subdistrict:en', 'emergency', 'electrified', 'direction', 'alt_name',
  'building:material', 'admin_level', 'motor_vehicle', 'addr:street:sym_ul',
  'brand', 'denotation', 'golf', 'area', 'restriction', 'addr:hamlet',
  'generator:source', 'fixme', 'frequency', 'addr:unit', 'wikipedia',
  'generator:method', 'tactile_paving', 'addr:neighbourhood', 'capacity',
  'religion', 'wetland', 'historic', 'name:ru', 'brand:wikidata', 'horse',
  'generator:type', 'fire_hydrant:type', 'usage', 'roof:colour',
  'roof:material', 'species', 'brand:wikipedia', 'nhd:reach_code',
  'generator:output:electricity', 'shelter', 'nhd:com_id', 'noexit',
  'location', 'mml:class', 'gnis:feature_id', 'fee', 'at_bev:addr_date',
  'nycdoitt:bin', 'raba:id', 'nhd:fdate', 'gnis:fcode', 'covered',
  'segregated', 'design', 'name:ar', 'name:zh', 'cuisine', 'level',
  'survey:date', 'gnis:ftype', 'crossing_ref', 'addr:streetnumber', 'route',
  'postal_code', 'backrest', 'name:ja', 'cycleway', 'bench', 'office',
  'addr:housename', 'traffic_sign', 'incline', 'lanes:backward', 'junction',
  'ford', 'lanes:forward', 'traffic_calming', 'information',
  'building:colour', 'is_in', 'addr:full', 'genus', 'crop', 'denomination',
  'fire_hydrant:diameter', 'turn:lanes', 'colour', 'hgv',
  'chicago:building_id', 'mtb:scale', 'gnis:created', 'building:use',
  'mapper', 'cables', 'addr:city:en', 'operator:wikidata', 'aeroway',
  'passenger_lines', 'name:ko', 'sac_scale', 'fire_hydrant:position',
  'destination', 'gnis:county_id', 'population', 'old_ref', 'gnis:state_id',
  'residential', 'construction', 'noname', 'addr:street:name',
  'circumference', 'note:ja', 'healthcare', 'addr:street:type', 'int_name',
  'trail_visibility', 'it:fvg:ctrn:code', 'kerb', 'it:fvg:ctrn:revision',
  'crossing:island', 'operator:type', 'contact:phone', 'cycleway:both',
  'motorcycle', 'ref:ruian', 'name:fr', 'maxspeed:type', 'addr:place:en',
  'operator:wikipedia', 'roof:orientation', 'lamp_type', 'name:uk',
  'motorcar', 'fence_type', 'addr:floor', 'email', 'seamark:type',
  'addr:region', 'nysgissam:review', 'old_name', 'int_ref',
  'traffic_signals', 'name:de', 'addr:street:prefix', 'official_name',
  'toll', 'tower:type', 'cycleway:right', 'building:roof', 'designation',
  'contact:website', 'addr:flats', 'lojic:bgnum', 'ref:linz:building_id',
  'addr:provisionalnumber', 'boat', 'seasonal', 'check_date', 'url',
  'addr:inclusion', 'indoor', 'lane_markings', 'name:fi', 'meadow',
  'water_source', 'building:condition', 'structure', 'roof:height',
  'traffic_signals:direction', 'lamp_mount', 'bin', 'destination:ref',
  'addr:county', 'ref:minvskaddress', 'landcover', 'name:pl', 'gnis:id',
  'route_ref', 'internet_access', 'house', 'network:wikidata', 'distance',
  'building:levels:underground', 'support', 'takeaway', 'bicycle_parking',
  'vehicle', 'substation', 'recycling_type', 'turn:lanes:forward',
  'name:etymology:wikidata', 'fid', 'seats', 'is_in:country',
  'network:wikipedia', 'short_name', 'railway:traffic_mode',
  'turn:lanes:backward', 'addr:ward', 'addr:village', 'living_street',
  'hiking', 'name:es', 'nhd:fcode', 'dibavod:id', 'population:date', 'from',
  'to', 'mapillary', 'building:usage:pl', 'nhd:ftype', 'image',
  'shelter_type', 'maxheight', 'trees', 'railway:pzb', 'supervised',
  'building:age', 'name:be', 'mvdgis:cod_nombre', 'craft', 'maxweight',
  'public_transport:version', 'piste:type', 'contact:email', 'addr:block',
  'comment', 'embankment', 'handrail', 'diameter_crown', 'mvdgis:padron',
  'linz2osm:objectid', 'circuits', 'import_uuid', 'isced:level', 'name:br',
  'building:fireproof', 'railway:signal:direction', 'railway:etcs',
  'placement', 'vending', 'motorroad', 'addr:block:en', 'heritage',
  'condition', 'moped', 'branch', 'is_in:state', 'content',
  'building:structure', 'taxon', 'addr:subward', 'parking_space',
  'ref:codcat', 'area:highway', 'species:de', 'lcn', 'step_count',
  'oneway:bicycle', 'railway:signal:position', 'aerialway', 'species:en',
  'network:type', 'railway:track_ref', 'train', 'unsigned_ref', 'local_ref',
  'zone:traffic', 'min_height', 'atm', 'usar_addr:edit_date',
  'zone:maxspeed', 'substance', 'smoking', 'industrial', 'prow_ref',
  'building:foundation_height', 'door', 'owner', 'departures_board',
  'outdoor_seating', 'wires', 'brand:en', 'mofa', 'button_operated',
  'operational_status', 'ramp', 'highway:category:pl', 'genus:en',
  'heritage:operator', 'cycleway:left', 'hgv:national_network', 'tracks',
  'contact:facebook', 'fax', 'name:sr', 'old_railway_operator',
  'building:use:pl', 'piste:difficulty', 'name:prefix', 'transformer',
  'name:he', 'payment:cash', 'nat_ref', 'is_in:county', 'osmc:symbol',
  'railway:lzb', 'tree:ref', 'railway:position', 'collection_times',
  'accuracy:meters', 'site', 'mtb:scale:uphill', 'is_in:city', 'loc_name',
  'artwork_type', 'board_type', 'traffic_signals:sound', 'border_type',
  'generator:solar:modules', 'drive_through', 'name:sv', 'manhole',
  'note:en', 'dcgis:gis_id', 'memorial', 'zone', 'dispensing',
  'toilets:wheelchair', 'abandoned:building', 'line_attachment',
  'addr:neighbourhood:en', 'surveillance', 'fhrs:id', 'operator:en',
  'golf_cart', 'waste', 'piste:grooming', 'parking:lane:both', 'length',
  'railway:preferred_direction', 'park_ride', 'addr:city:de',
  'capacity:disabled', 'line', 'addr:city:it', 'military', 'colour:back',
  'highspeed', 'communication:mobile_phone', 'maxaxleload',
  'surveillance:type', 'gnis:county_name', 'colour:text', 'ncat',
  'advertising', 'nat_name', 'garden:type', 'psv', 'loc_ref', 'note:city',
  'shoulder', 'opening_hours:covid19', 'uic_ref', 'site_type',
  'crossing:barrier', 'railway:radio', 'alt_name:en', 'playground',
  'light:method', 'par', 'building:min_level', 'recycling:glass_bottles',
  'name:ja_rm', 'name:it', 'stop', 'addr:town', 'colour:arrow',
  'social_facility', 'addr:quarter', 'gtfs_id', 'ruins', 'inscription',
  'drinking_water', 'informal', 'species:it', 'maxspeed:forward',
  'addr:street:it', 'standing', 'cemetery', 'abandoned:railway',
  'addr:street:de', 'traffic_signals:vibration', 'ward', 'teryt:simc',
  'seamark:name', 'couplings', 'maxspeed:backward', 'est_width', 'light:lit',
  'official_status', 'review', 'camera:type', 'adr_les', 'product',
  'addr:postcode:source', 'recycling:paper', 'name:ca', 'toilets:disposal',
  'fuel:diesel', 'snowmobile', 'symbol', 'proposed', 'lamp_flames',
  'dcgis:captureyear', 'wood', 'internet_access:fee', 'camera:mount',
  'is_in:country_code', 'note:post_town', 'geobase:uuid', 'operator:ja',
  'addr:source', 'abandoned', 'depth', 'healthcare:speciality', 'ref:nsrq',
  'lamp_ref', 'manufacturer', 'reg_ref', 'ownership', 'bollard', 'pump',
  'payment:credit_cards', 'genus:it', 'payment:coins', 'location:transition',
  'fire_hydrant:pressure', 'addr:block_number', 'dataset', 'detail',
  'diameter', 'network:short', 'ref:miabldg', 'ref:sandre', 'name:ga',
  'building:walls', 'tram', 'light:count', 'bmo:type', 'name:th',
  'contact:instagram', 'overtaking', 'ref_name', 'workrules',
  'ref:linz:topo50_id', 'name:zh_pinyin', 'is_in:village', 'disused',
  'uic_name', 'street_cabinet', 'parking:lane:right', 'voltage:primary',
  'source_ref:url', 'light_source', 'hazmat', 'railway:position:exact',
  'surrey:addrid', 'salt', 'name:el', 'recycling:glass', 'surrey:date',
  'is_in:continent', 'trolley_wire', 'tidal', 'rer_edi_id:ref',
  'is_in:region', 'produce', 'light:colour', 'name:ar1', 'agricultural',
  'abutters', 'contact:fax', 'ssr:stedsnr', 'protect_class',
  'historic:civilization', 'surface_survey', 'brand:ja', 'status',
  'priority_road', 'name:kn', 'toll:hgv', 'voltage:secondary',
  'destination:street', 'locality', 'addr:parish', 'date', 'government',
  'maxspeed:hgv', 'name:nl', 'object:street', 'import_ref',
  'railway:bidirectional', 'addr:nostreet', 'cutting', 'unisex',
  'fuel:octane_95', 'delivery', 'post_box:type', 'ewmapa:warstwa',
  'length_unit', 'wikimedia_commons', 'crossing:light',
  'passenger_information_display', 'route_master', 'genus:de', 'ref:old',
  'payment:visa', 'parking:lane:left', 'destination:lanes', 'statscan:rbuid',
  'bridge:structure', 'mtb', 'capital', 'tree_form', 'age', 'constituency',
  'utility', 'plot_number', 'site_name', 'ref:usrn', 'light:tilt',
  'building:type:pl', 'height:range', 'social_facility:for', 'gst:feat_id',
  'disused:railway', 'object:city', 'ref:opendataparis:domanialit',
  'tower:construction', 'switch', 'species:ro', 'ref:findr', 'dcgis:square',
  'payment:mastercard', 'artist_name', 'recycling:clothes',
  'traffic_sign:forward', 'lbcs:activity:code', 'lbcs:function:code',
  'lbcs:activity:name', 'dcgis:lot', 'light:shape', 'floating',
  'de:strassenschluessel', 'lbcs:function:name', 'importance', 'pipeline',
  'is_in:municipality', 'wheelchair:description', 'floor:material',
  'end_date', 'surveillance:zone', 'strazakosm:send_date',
  'strazakosm:sender_id', 'gnis:feature_type', 'destination:forward',
  'name:genitive', 'dog', 'loading_gauge', 'is_in:province',
  'maxspeed:hgv:conditional', 'capacity:persons', 'bdouble',
  'maxspeed:conditional', 'toilets', 'bak:fac_type1',
  'railway:milestone:catenary_mast', 'name:ur', 'project', 'ref:addr',
  'protection_title', 'roof:direction', 'seamark:topmark:shape',
  'railway:gnt', 'logainm:ref', 'logainm:url', 'fire_operator',
  'payment:debit_cards', 'contact:vk', 'railway:signal:main:form',
  'roundtrip', 'toilets:position', 'ski', 'railway:signal:main', 'nvdb:id',
  'b5m:url', 'b5m:id', 'field_name', 'swimming_pool', 'bak:fac_type2',
  'rcn_ref', 'maxspeed:bus', 'destination:backward', 'name:hu',
  'seamark:buoy_lateral:colour', 'demolished:building', 'noref',
  'name:ja_kana', 'nhd-shp:fdate', 'minspeed', 'waterway:type', 'nvdb:date',
  'clothes', 'pillar:type', 'attraction', 'name:eu', 'maxspeed:advisory',
  'converted_by', 'hedge', 'lanes:both_ways', 'subway', 'nhd-shp:com_id',
  'room', 'railway:switch', 'bridge:name', 'stars', 'name:oc', 'accuracy',
  'maxspeed:trailer', 'abandoned:highway', 'seamark:buoy_lateral:category',
  'seamark:buoy_lateral:shape', 'clc:code', 'building:ownership',
  'mtb:scale:imba', 'design:ref', 'time', 'cycleway:surface',
  'building:place', 'seamark:mooring:category', 'gnis:import_uuid',
  'divipola', 'cutline', 'junction:ref', 'typhoon:damage',
  'railway:track_class', 'note:addr_place', 'name:lt',
  'seamark:topmark:colour', 'marker', 'seamark:light:colour',
  'recycling:cans', 'name:ro', 'is_in:town', 'level:ref', 'gnis:reviewed',
  'name:cs', 'snowplowing', 'taxon:species', 'ref:opendataparis:adresse',
  'recycling:plastic', 'basin', 'railway:local_operated', 'ref:penndot',
  'protected', 'building:floor_area', 'building:state_of_the_house',
  'building:fi:id', 'access:roof', 'hazard', 'crossing:bell',
  'seamark:light:character', 'addr:subcounty', 'waterway:llid',
  'railway:turnout_side', 'goods', 'building:use:residential', 'handicap',
  'expressway', 'building:category_of_the_house', 'operator:short',
  'road_marking', 'nhd-shp:fcode', 'name:etymology:wikipedia',
  'plant:source', 'top_ele', 'side', 'footway:surface',
  'railway:signal:main:states', 'map_type', 'resource', 'noaddress',
  'map_size', 'seamark:buoy_lateral:system', 'name:hi', 'mooring',
  'change:lanes', 'railway:ls', 'parking:orientation', 'via',
  'diet:vegetarian', 'editor', 'self_service', 'royal_cypher', 'tmc',
  'railway:ref', 'traffic_sign:backward', 'odbl', 'gvr:code',
  'highway_authority_ref', 'destination:symbol', 'population:pupils:2015',
  'ssr:type', 'disused:amenity', 'camera:direction', 'name:fa',
  'railway:signal:main:function', 'population:pupils:2012',
  'hgv:state_network', 'ephemeral', 'old_ref_legislative', 'zoning',
  'cosmha', 'fuel:octane_98', 'mml:ref', 'maintenance', 'contact:twitter',
  'hcpaogis:dorcode', 'maxwidth', 'male', 'name:nan', 'ref:en',
  'reservoir_type', 'rwn_ref', 'location:accuracy', 'name:ka',
  'lamp_operator', 'country', 'utahagrc:parcelid', 'telecom', 'trailblazed',
  'reg_name', 'rooms', 'plant:output:electricity', 'club', 'ref:mhs',
  'fire_hydrant:street', 'id', 'name:pt', 'building:cladding',
  'addr:community', 'female', 'lamp_model', 'change:lanes:forward',
  'visibility', 'sidewalk:right', 'building:roof:shape', 'source_date',
  'railway:switch:electric', 'old_ref:1945', 'network:guid', 'nohousenumber',
  'turn:lanes:both_ways', 'maxstay', 'change:lanes:backward', 'koatuu',
  'architect', 'payment:notes', 'cesena:ref_id', 'trolleybus',
  'building:architecture', 'logging:start_date', 'couplings:diameters',
  'note:old_railway_operator', 'old_name:ru', 'motorboat',
  'construction_date', 'nhd:gnis_id', 'railway:track_type',
  'maxspeed:source', 'wall:material', 'old_addr:housenumber',
  'fire_hydrant:housenumber', 'id_origin', 'damage',
  'railway:signal:main:height', 'light:direction', 'working',
  'check_date:opening_hours', 'railway:signal:speed_limit',
  'mhs:inscription_date', 'railway:signal:speed_limit:form', 'name:en1',
  'phases', 'seamark:rock:water_level', 'species:es', 'fvst:navnelbnr',
  'line_management', 'railway:signal:distant', 'njgin:guid',
  'railway:signal:distant:form', 'unocha:pcode', 'addr:division',
  'flour_fortified', 'disused:shop', 'old_ref:legislative', 'ref:colour',
  'sidewalk:left', 'damage:event', 'seamark:light:period', 'building:floor',
  'contact:youtube', 'carriageway_ref', 'todo', 'name:my', 'taxon:family',
  'railway:signal:minor:form', 'traffic_sign:direction', 'flood_prone',
  'clc:id', 'ref:zh', 'addr:hamlet:de', 'addr:hamlet:it', 'smoothness:date',
  'traffic_sign:2', 'railway:signal:speed_limit:speed', 'mountain_pass',
  'check_date:surface', 'is_in:state_code', 'railway:kvb',
  'maxweight:signed', 'katotth', 'backup_generator', 'railway:signal:minor',
  'addr:city:ar', 'taxon:pt', 'species:fr', 'plant:method',
  'reporting_marks', 'source_type_imagery', 'gtfs_stop_code',
  'fire_hydrant:type:zh', 'fuel:lpg', 'sby:bldgtype', 'second_hand',
  'air_conditioning', 'bunker_type', 'railway:atb', 'access:conditional',
  'chile:region', 'irrigation', 'name:ku', 'nat_name:en',
  'dibavod:needs:review', 'note:de', 'driveway', 'memorial:type',
  'ref:vatin', 'heritage:website', 'ref:cadastre', 'landform',
  'national_highways:area', 'catastro:ref', 'name:etymology',
  'old_addr:place', 'payment:maestro', 'name:bg', 'allotments',
  'enforcement', 'official_name:en', 'opening_date',
  'parking:condition:both', 'note:es', 'hoops', 'ngbe:yutm_ed50',
  'ngbe:xutm_ed50', 'catastro:codigo', 'ngbe:tema', 'ngbe:subgrupo',
  'ngbe:huso', 'ngbe:grupo', 'name:right', 'name:vi', 'name:left', 'ngbe:id',
  'ngbe:lat_ed50', 'ngbe:codigo', 'ngbe:lon_ed50', 'ngbe:version',
  'ngbe:hojabcn25', 'ngbe:tipotexto', 'railway:signal:distant:states',
  'taxon:cultivar', 'passenger', 'class:bicycle:mtb', 'share_taxi',
  'old_name:en', 'recycling:plastic_bottles', 'maxspeed:practical',
  'fire_hydrant:city', 'ref:ine', 'sides', 'stile', 'axle_load', 'pole',
  'manufacturer:type', 'rednap:latitud', 'rednap:longitud', 'rednap:numero',
  'rednap:tipo', 'rednap:codigoine', 'rednap:posicion', 'rednap:ficha',
  'rednap:grupo', 'rednap:nodo', 'genus:fr', 'gtfs:stop_id', 'ref:ar',
  'railway:signal:speed_limit:height', 'platform:width', 'elevation',
  'ref:oslo:tree', 'seamark:beacon_lateral:category', 'llid',
  'razed:railway', 'stream', 'stop_id', 'rotor:diameter', 'model',
  'parking:condition:right', 'min_age', 'winter_service', 'name:hsb',
  'name:cy', 'heritage:ref', 'paloalto_ca:id', 'surface:grade',
  'rednap:altitudortometrica', 'species:wikidata', 'ref:caclr',
  'railway:signal:distant:height', 'diet:vegan', 'handrail:left',
  'handrail:right', 'seamark:source', 'defibrillator:location',
  'subject:wikidata', 'taxi', 'path', 'name:tr', 'ele:accuracy',
  'note:cadastre:building_use', 'description:de', 'service_times',
  'cycleway:right:lane', 'ref:lor', 'animated', 'telecom:medium',
  'crossing:saltire', 'ref:colour_tx', 'lamp_model:de', 'clc:year', 'grades',
  'farmland', 'traces', 'school:type_idn', 'note:cadastre:id',
  'object:postcode', 'bus:lanes', 'ref:edubase', 'teryt:rm', 'ref:fid',
  'hov', 'tumulus', 'message', 'name:mk', 'dcgis:featurecode', 'station',
  'flag:type', 'generator:place', 'cycle_network', 'fireplace',
  'couplings:type', 'changing_table', 'stroller', 'railway:tbl',
  'contact:mobile', 'rcn', 'recycling:plastic_packaging', 'contact:street',
  'reservation', 'object:country', 'traffic', 'sidewalk:both:surface',
  'garmin_type', 'beauty', 'ref:cadc:2020', 'luminous', 'structure_gauge',
  'facebook', 'levels', 'memorial:addr', 'recycling:waste', 'canal',
  'contact:ok', 'roof:orientation:compass', 'kvl_hro:type',
  'destination:ref:lanes', 'building:adjacency', 'land_property', 'narrow',
  'socket:type2', 'rating', 'operator:ja_rm', 'emergency_telephone_code',
  'sorting_name', 'motor_vehicle:conditional', 'contact:housenumber',
  'network:en', 'organic', 'name:hy', 'castle_type', 'teryt:stan_na',
  'maxspeed:variable', 'gritting',
  'railway:milestone:emergency_brake_override', 'duration',
  'railway:signal:main:substitute_signal', 'highway:class:pl',
  'destination:ref:to', 'ref:kystverket', 'okato:user',
  'seamark:beacon_lateral:colour', 'ship', 'exit', 'recycling:cardboard',
  'bridge:support', 'railway:signal:minor:height', 'charge', 'ref:mise',
  'toilets:access', 'addr:union', 'seamark:notice:function',
  'payment:american_express', 'seamark:notice:category', 'wood:age',
  'max_age', 'addr:locality', 'old_name:uk', 'tents', 'ref:type',
  'memorial:text', 'class:bicycle', 'fhrs:authority', 'tree:ref_area',
  'fhrs:local_authority_id', 'disused:highway', 'conveying', 'light_rail',
  'year_of_construction', 'parking:condition:left', 'canoe',
  'seamark:light:range', 'diocese', 'census:population', 'railway:ctcs',
  'acres', 'seamark:light:height', 'opening_hours:signed', 'turn',
  'description:en', 'shape:plan', 'curve_geometry', 'ref:vayla', 'tomb',
  'display', 'siruta:code', 'was:building', 'seamark:beacon_lateral:shape',
  'gfoss_id', 'listed_status', 'building:level', 'roof:downpipe',
  'land_area', 'gutter', 'cycleway:both:lane', 'typhoon:reviewed', 'order',
  'name:pa', 'contact:postcode', 'code', 'gnis:edited',
  'building:facade:colour', 'redwood_city_ca:bld_gid', 'oneway:moped',
  'fdot:sis', 'roof:ridge', 'oneway:mofa', 'toilets:handwashing',
  'addr:street:fr', 'object:suburb', 'ramp:wheelchair', 'navigationaid',
  'ferry', 'railway:rail', 'contact:city', 'ref:cadc:2019',
  'arpav_codice_bacino', 'railway:signal:minor:states', 'format', 'brand:zh',
  'expected_rwn_route_relations', 'railway:atc', 'not:name', 'dcgis:dataset',
  'seamark:beacon_lateral:system', 'triple_tower', 'seamark:light:reference',
  'hgv:lanes', 'gtfs:feed', 'fire_hydrant:description',
  'arpav_codice_sottobacino', 'teryt:updated_by', 'placement:forward',
  'generator:orientation', 'piste:oneway', 'power_supply', 'hwpi',
  'mtb:type', 'abandoned:man_made', 'toll:bus', 'old_ref:fap', 'species:no',
  'maxweight:conditional', 'maxlength', 'designated_direction',
  'redwood_city_ca:addr_id', 'toilets:num_chambers', 'cycleway:right:oneway',
  'kerb:height', 'disused:building', 'townhall:type', 'ramp:stroller',
  'design:incomplete', 'source_ref:name', 'official_ref', 'practicability',
  'addr2:street', 'addr2:housenumber', 'note:address_buildingnumber',
  'ntd_id', 'note:name', 'gtfs:release_date', 'complete', 'caravans',
  'name:tt', 'triangulation_point', 'capacity:parent', 'lockable',
  'old_name:de', 'ref:corine_land_cover', 'piste:name', 'pcode', 'name:en2',
  'removed:building', 'wikipedia:ru', 'object:citydistrict',
  'construction:railway', 'tunnel:name', 'species:wikipedia', 'icao',
  'addr:place:it', 'operational_status_quality', 'damage:assessment',
  'sidewalk:right:surface', 'fuel:e10', 'damage:type', 'capacity:women',
  'cai_scale', 'railway:signal:shunting', 'lamp_ref_swd', 'maxspeed:lanes',
  'uuid:building', 'building:height', 'payment:contactless', 'addr:place:de',
  'railway:signal:shunting:form', 'wood:density', 'ref:psma:loc_pid',
  'building_type', 'ref:bag:old', 'network:zh', 'zhb_code', 'note:lanes',
  'recycling:shoes', 'kvl_hro:amenity', 'mechanical', 'beds', 'local_code',
  'fdot:fihs', 'health_facility:type', 'source_ref:maxspeed', 'is_in:suburb',
  'ref:cobe', 'guidepost', 'aquaculture', 'nsdi_code', 'operator:website',
  'hide', 'full_name', 'ref:anncsu', 'ref:cue', 'name:ml', 'diplomatic',
  'name:sq', 'osm_id', 'railway:signal:speed_limit_distant', 'nat_name:ja',
  'railway:signal:speed_limit_distant:form', 'name:af',
  'person:date_of_birth', 'ascent', 'communication', 'ref_catastral',
  'railway:scmt', 'gid', 'deanery', 'building_status', 'name:gl',
  'fuel:octane_92', 'evacuation_center', 'railway:signal:shunting:height',
  'esr:user', 'interval', 'ref:zsj', 'payment:telephone_cards', 'animal',
  'authentication:membership_card', 'ref:ruian:street', 'name:az',
  'ewmapa:kod_znakowy', 'salting:ref', 'old_postal_code', 'maritime',
  'building:type', 'it:fvg:regional_catalog:corsi_acqua:caratteristica',
  'it:fvg:regional_catalog:corsi_acqua:codice_fvg', 'name:ta', 'grassland',
  'sloped_curb', 'transport:zone', 'destination:colour', 'is_in:district',
  'brand:ru', 'siruta:code_sup', 'siruta:county_code', 'siruta:county',
  'siruta:type', 'siruta:county_id', 'siruta:name_sup',
  'population:census:1992', 'name:ug', 'video', 'alt_name:ar',
  'recycling:batteries', 'name:ps', 'bicycle_road', 'oktmo:user', 'full_id',
  'postal_code:source', 'ref:nid', 'metcouncil:site_id',
  'metcouncil:nroutes', 'seamark:beacon_isolated_danger:shape',
  'coa:place_id', 'name:ms', 'metcouncil:site_at', 'metcouncil:city_id',
  'metcouncil:site_on', 'metcouncil:dfz', 'metcouncil:site_hfn',
  'metcouncil:corner_loc', 'metcouncil:corn_desc', 'metcouncil:sat_trips',
  'metcouncil:wkdy_trips', 'metcouncil:sun_trips', 'ref:colour_bg', 'notes',
  'check_date:crossing', 'addr:door', 'ramp:bicycle', 'operator:ar',
  'unmil:id', 'playground:theme', 'payment:electronic_purses',
  'metcouncil:routes', 'seamark:harbour:category', 'roof:angle',
  'maxspeed:tilting', 'alt_name:zh', 'ref:linz:hydrographic_id', 'automated',
  'recycling:scrap_metal', 'name:kk', 'gtfs:addr:housenumber', 'gate:type',
  'state', 'name:prefix:ru', 'seamark:light:group', 'plant_community:it',
  'restaurant', 'fuel:cng', 'seamark:distance_mark:category',
  'project:mappingforniger', 'mappingdc:gid', 'note:relevance',
  'seamark:distance_mark:distance', 'brewery', 'seamark:distance_mark:units',
  'health_level', 'light:mount', 'crossing:activation',
  'railway:signal:speed_limit_distant:speed', 'iucn_level', 'lamp:shape',
  'bbr:husnummer', 'de:regionalschluessel', 'fire_hydrant:couplings',
  'ocean', 'survey_point', 'roof:edge', 'post_office:type', 'roof',
  'community_centre', 'railway:preserved', 'booth', 'median',
  'cycling_width', 'destination:lang:en', 'lcn_ref', 'implicit', 'subject',
  'sagns_id', 'fire_hydrant:coupling_type', 'gtfs_location_type', 'istat_id',
  'name:bn', 'construction:railway:etcs', 'osm_type', 'brand:website',
  'ine:municipio', 'de:amtlicher_gemeindeschluessel', 'historic:railway',
  'abandoned:place', 'mtb:name',
  'it:fvg:regional_catalog:corsi_acqua:bacino', 'bottle', 'lock',
  'recycling:green_waste', 'waterway:sign', 'railway:signal:combined',
  'seamark:landmark:category', 'survey:name', 'ref:fgkz', 'tourist_bus',
  'category', 'railway:signal:combined:form', 'ewmapa:funkcja',
  'socket:type2:output', 'sidewalk:left:surface', 'zip_right',
  'highway:category', 'railway:ballastless', 'wiki:symbol', 'access:lanes',
  'internet_access:ssid', 'flow_rate', 'district', 'except',
  'seamark:recommended_track:minimum_depth', 'megalith_type', 'backcountry',
  'target', 'domanialite', 'building:roof:colour', 'historic:period',
  'lanes:psv', 'access:delivery', 'swing_gate:type', 'change:backward',
  'chile:surface', 'name:pnb', 'alt_name:ru', 'ref:inspire', 'map',
  'railway:signal:speed_limit_distant:height', 'piste:lit', 'disused:name',
  'authoritative', 'fortification_type', 'adot_name', 'buildingpart',
  'check_date:shelter', 'payment:ep_ipass', 'horse_scale', 'fitness_station',
  'service:bicycle:repair', 'size', 'ice_road',
  'parking:lane:right:parallel', 'passing_places', 'flag:name',
  'railway:signal:shunting:states', 'gtfs:route_id', 'damage:review_date',
  'flag:wikidata', 'building:soft_storey', 'id_ob', 'payment:visa_electron',
  'brand:uk', 'name:lv', 'zip_left', 'survey_point:zh', 'payment:jcb',
  'railway:signal:distant:repeated', 'payment:cards', 'damage:organization',
  'building:overhang', 'shape:elevation', 'damage:reconstruction',
  'toilets:number', 'seamark:buoy_special_purpose:colour', 'traffic_sign:3',
  'waste_basket', 'addr:street:eu', 'ref:gss', 'description:covid19',
  'maxspeed:psv:conditional', 'railway:tilting', 'name:azb',
  'access_control', 'osmc:name', 'fog', 'building:use:parking', 'teryt:typ',
  'name:eo', 'sourcedb:id', 'official_short_type', 'surface:colour',
  'seamark:notice:impact', 'seamark:buoy_special_purpose:shape',
  'old_network', 'name:zh_zhuyin', 'technology', 'change:forward',
  'capacity:pupils', 'ts_calle', 'ts_orientacion', 'name:yue',
  'construction:voltage', 'ts_hacia', 'capacity:teachers',
  'water_tank:volume', 'ts_codigo', 'construction:frequency',
  'razed:building', 'guest_house', 'gtfs:name', 'toilet:num_chambers',
  'recycling:paper_packaging', 'gritting_operator', 'ts_desde',
  'expected_rcn_route_relations', 'construction:electrified', 'flats',
  'note:pt', 'seamark:light:1:colour', 'political_division',
  'seamark:buoy_cardinal:category', 'related_law', 'notas',
  'seamark:buoy_cardinal:colour', 'orientation', 'checkpoint',
  'old_operator', 'seamark:buoy_cardinal:colour_pattern', 'railway:ctc',
  'brand:ar', 'seamark:light:1:character', 'bridge:ref', 'proposed:voltage',
  'name:hr', 'name:be-tarask', 'proposed:frequency', 'crossing:supervision',
  'lit_by_gaslight', 'name:sl', 'seamark:buoy_cardinal:shape', 'vitality',
  'name:mr', 'restriction:conditional', 'utilization', 'embassy',
  'railway:signal:combined:function', 'trade', 'frontage_road', 'region',
  'payment:diners_club', 'iata', 'name:source', 'carriage',
  'payment:girocard', 'species:nl', 'ign:longitud', 'ign:latitud',
  'name:kn:iso15919', 'ign:red', 'name:full', 'river:waterway_distance',
  'shoulder:right', 'geological', 'maxspeed:designed', 'cycleway:left:lane',
  'cash_in', 'descent', 'wood:origin', 'recycling:newspaper', 'gdot:grip',
  'ref:fra_crossing', 'genus:ru', 'seamark:notice:orientation',
  'destination:ref:forward', 'parking:lane:both:parallel', 'is_sidepath',
  'destination:int_ref', 'cycleway:right:segregated', 'ref:gnbc',
  'seamark:notice:system', 'operator2', 'name:ne', 'cycleway:left:oneway',
  'note:pl', 'school', 'name:ber', 'data_zmiany', 'addr:city:fr',
  'seamark:light:1:height', 'recycling:magazines', 'aerialway:occupancy',
  'is_in:commune', 'destination:ref:backward', 'disabled',
  'proposed:electrified', 'mtb:winter', 'seamark:light:1:range',
  'seamark:bridge:category', 'gritting_route_ref', 'addr:settlement',
  'payment:discover_card', 'in_service', 'dual_carriageway', 'lwn_name',
  'source_ref:ref', 'disc_golf', 'seamark:small_craft_facility:category',
  'bonnet:colour', 'direction_north', 'is_in:cercle', 'parking:fee',
  'service:bicycle:retail', 'payment:visa_debit', 'was:highway',
  'camera:angle', 'managed', 'name:ckb',
  'it:fvg:regional_catalog:corsi_acqua:sottobacino', 'direction_south',
  'operator:abbr', 'ref:gid', 'busway:right', 'fire_rank', 'fcode',
  'url:crfop', 'hgv:conditional', 'communication:radio', 'alt_name:be',
  'access:disabled', 'delivery:covid19', 'source_dat', 'compressed_air',
  'bak:fac_type3', 'name:mi', 'is_in:clan', 'emergency:phone', 'fuel',
  'protection_title:pl', 'taxon:species:varietas',
  'railway:maxspeed:diverging', 'name:la', 'fuel:octane_91', 'rental',
  'postal_code_level', 'direction_east', 'name:sw', 'species:pl', 'task',
  'addr:city:lld', 'garden:style', 'steps', 'faa', 'omkum:old_name', 'bar',
  'name:etymology:description', 'diet:halal', 'parking:lane:left:parallel',
  'maxspeed:freight', 'psv:lanes', 'ref:at:bda', 'atv', 'heritage:since',
  'rtsa_scale', 'centre_turn_lane', 'verified', 'railway:switch:heated',
  'survey_date', 'seamark:light:sequence', 'ref:hinder', 'parish', 'bus_bay',
  'addr:place:zh', 'direction_west', 'alt_name:zh_pinyin',
  'monitoring:weather', 'name:kab', 'clc:code_06',
  'destination:symbol:lanes', 'nga:ufi', 'fdot:ref', 'governance_type',
  'cycleway:right:bicycle', 'light:lux', 'description:it',
  'ref:street_cabinet', 'towpath', 'seamark:beacon_special_purpose:category',
  'prominence', 'species:ja', 'placement:backward', 'idee:name',
  'survey_point:structure', 'strassen-nrw:abs', 'roof:cover:material',
  'maxspeed:advised', 'name:md', 'lanes:bus', 'building:irregularity',
  'roof_shade:present', 'building:groundslope', 'official_vicinal_ref',
  'physical:condition', 'tree_location:city', 'format:top', 'westra_ref',
  'toilet:handwashing', 'name:id', 'overtaking:hgv', 'bag:bronwoonplaats',
  'food', 'asset_ref', 'idp:camp_site', 'glacier:edge', 'source_type_survey',
  'wall:thickness', 'railway:evm', 'crown_type', 'addr:contact', 'busway',
  'paved:date', 'cyclestreet', 'tower:shape', 'operator:ru',
  'is_sidepath:of', 'name:da', 'cap:colour',
  'it:fvg:regional_catalog:corsi_acqua:natura', 'name:sk', 'symbol:it',
  'destroyed:building', 'tree_location:full', 'authentication:app', 'lines',
  'name:sd', 'vending_machine', 'museum', 'name:cv', 'foot:conditional',
  'addr:street:lld', 'timetable', 'name:tk', 'addr:zone', 'ref:catasto',
  'seamark:light:1:period', 'carriageway', 'recording:manually',
  'bicycle:lanes', 'wikipedia:en', 'seamark:light:1:sector_end', 'reef',
  'working:test_date', 'railway:signal:combined:states',
  'seamark:topmark:information', 'fut_ref', 'obstacle', 'pihatie',
  'seamark:light:1:sector_start', 'operator:uk', 'sanitary_dump_station',
  'bridge:name:en', 'name:no', 'is_sidepath:of:name', 'local_class',
  'railway:signal:combined:height', 'name:mn', 'operator:wikipedia:en',
  'maxspeed:coach', 'fire_hydrant:water_source', 'name:signed', 'blockage',
  'remark', 'plant', 'roof:structure', 'maxweight:hgv',
  'number_of_apartments', 'fishing', 'bicycle:conditional',
  'it:fvg:regional_catalog:corsi_acqua:nome', 'address', 'kodinspire',
  'railway:signal:snowplow', 'railway:signal:snowplow:form',
  'payment:bitcoin', 'embedded_rails', 'destination:lang:ar',
  'ref:start_date', 'operator:zh', 'seamark:beacon_special_purpose:colour',
  'name:en3', 'seamark', 'locked', 'service:vehicle:car_repair',
  'genus:wikidata', 'bicycle_rental', 'faces', 'service:bicycle:pump',
  'ref:source', 'damaged', 'vertical_irregularity', 'microbrewery',
  'railway:signal:snowplow:type', 'dump:official', 'description:fr', 'cover',
  'rcrc_ref', 'lastcheck', 'ref:csioz', 'hazmat:water', 'name_3', 'logging',
  'maaamet:orig_tunnus', 'opendata:type', 'soft_storey', 'addr:street:nl',
  'abandoned:date', 'railway:jkv', 'studio', 'school:type', 'lwn',
  'post_box:design', 'mobile', 'height:hub', 'ref:category',
  'pmfsefin:idedif', 'cycleway:right:surface', 'monitoring:water_level',
  'recycling:cartons', 'operator:wikipedia:ar', 'scenic',
  'seamark:shoreline_construction:category', 'school:gender', 'name:et',
  'groundcheck', 'proposed:highway', 'survey_point:purpose',
  'check_date:capacity', 'communication:microwave', 'name:uz', 'tipo_const',
  'display:analog', 'emergency:social_facility', 'subject:wikipedia',
  'imagery_used', 'shower', 'vrr:wabe', 'building:roof:orientation',
  'emergency:amenity', 'takeaway:covid19', 'ref:gurs:sta_sid', 'submarine',
  'addr:parentstreet', 'ref:zone:code', 'left:country', 'water_supply',
  'electricity', 'direction_southwest', 'ref:red', 'gtfs:trip_id:sample',
  'ref:microred', 'project:opencities_abidjan', 'direction_northeast',
  'onkz', 'private', 'whitewater', 'orchard', 'school:selective',
  'avalanche_protection', 'ref_no', 'cycleway:est_width', 'busway:left',
  'asb', 'emergency:social_facility:for', 'object:id', 'ref:vcgi:esiteid',
  'forestry', 'payment:cryptocurrencies', 'sbc_apn', 'sbc_parcel', 'sbc_id',
  'maxspeed:zone', 'meter_load', 'ref:sortere', 'authentication:contactless',
  'ref_trips', 'removed:power', 'nat_name:fr', 'nombre_estadisticas',
  'name:fy', 'priority', 'winter_road', 'direction_northwest', 'pylon:shape',
  'width:lanes', 'overtaking:hgv:conditional',
  'seamark:topmark:national_information', 'diet:kosher', 'historic:gauge',
  'survey', 'seamark:notice:information', 'snowplowing:category',
  'crossing:signals', 'metre_load', 'ref:nrhp', 'direction_southeast',
  'recycling:beverage_cartons', 'name:mzn', 'railway:signal:stop', 'ref:bkk',
  'whitewater:rapid_grade', 'addr:city:ru', 'ekatte', 'climbing',
  'seamark:light:2:colour', 'towards', 'addr:city:nl', 'placenamesni:url',
  'placenamesni:ref', 'seamark:light:2:character', 'seamark:information',
  'access:covid19', 'hov:lanes', 'garmin_road_class', 'grass',
  'is_in:health_level6', 'addr:street:es', 'fee_zone', 'alt_ref',
  'railway:signal:stop:form', 'destination:lanes:forward', 'name:gd',
  'alt_name:ca', 'note:it', 'sidewalk:surface', 'right:country',
  'cycleway:lane', 'monument', 'maxgcweight', 'window', 'lamp:power',
  'rwn:name', 'lift_gate:type', 'text1', 'mvdgis:source', 'handrail:center',
  'holding_position:type', 'is_in:territoire', 'destination:network',
  'socket:type2_combo', 'crane:type', 'ref:rce', 'brand:wikipedia:ar',
  'building:parts', 'description:zh', 'name_disaster', 'name:se',
  'duration:forward', 'building:lateral:system', 'operator_type',
  'voltage-high', 'sidewalk:both', 'boules', 'emergency:social_facility:id',
  'colour:bonnet', 'contents', 'start', 'vicinal_ref', 'rack',
  'railway:maxspeed:straight', 'survey_point:type',
  'emergency:social_facility:source', 'seamark:light:category', 'double',
  'source_type_walking_paper', 'ref:highway', 'aerialway:access',
  'proposed:railway', 'payment:ep_easycard', 'building:geological_site',
  'building:lateral:material', 'abandoned:power', 'hinge', 'addr:suburb:en',
  'shoulder:width', 'socket:chademo', 'emergency:shelter_type',
  'ref:gurs:hs_mid', 'sector', 'beacon:type',
  'seamark:beacon_special_purpose:shape', 'column:size:length',
  'column:size:breadth', 'lamp:count', 'vayla_id', 'name:am',
  'destination:to', 'seamark:retro_reflector:colour', 'exit_to',
  'railway:signal:electricity:form', 'name:statcan_rbuid',
  'dcgis:capturedate', 'railway:signal:electricity', 'siren:purpose',
  'was:name', 'name:te', 'recycling:organic', 'parcel_mail_in',
  'fire_hydrant:note', 'emergency:social_facility:association_villages',
  'seamark:bridge:clearance_height', 'valley', 'place_county',
  'roller_coaster', 'generator:manufacturer', 'navibot:categorize',
  'name:ua', 'seamark:notice:addition', 'colour:cap', 'fire_hydrant:count',
  'building:entrances', 'stairs', 'napervillegis:objectid', 'nist:fips_code',
  'parking:condition:right:time_interval', 'grande_circulation',
  'destination:lanes:backward', 'service:vehicle:tyres', 'door:wings',
  'linz:garmin_type', 'parking:condition', 'railway:signal:electricity:type',
  'ref:lfd', 'lock_name', 'destination:colour:lanes', 'fuel:e85',
  'description:es', 'name:gsw', 'alt_name:fr', 'addr:barangay',
  'fire_hydrant:flow_capacity', 'wifi', 'maxspeed:towing',
  'official_name:uk', 'ref:vatin:hu', 'object:housenumber', 'hazard_type',
  'vayla_cdate', 'car', 'short_name:en', 'roof:material:type', 'abbr_name',
  'cycleway:left:segregated', 'ncn_ref', 'railway:tvm', 'functional_class',
  'building:gable_wall', 'vehicle:conditional', 'physical_condition',
  'retrofit', 'irrigated', 'name:tl', 'building:bay:y', 'building:bay:x',
  'two_sided', 'traffic_signals:foot', 'zcen2011', 'addr:milestone',
  'ref:prng', 'addr:word', 'name:os', 'taxon:en', 'cycle_barrier',
  'division_code', 'railway:signal:distant:shortened', 'ssr:date',
  'currency:others', 'alt_name:zh_zhuyin', 'name:ks', 'buoy',
  'opening_hours:url', 'ssr:gruppe', 'ssr:hovedgruppe', 'brand:es',
  'project:pdevii', 'gtfs:trip_id:like', 'alt_name:de', 'shortest_name',
  'name:lb', 'aerialway:capacity', 'payment:easycard',
  'community_centre:for', 'name:alt', 'shelter_ref', 'mtb:description',
  'seamark:topmark:orientation', 'osmc:status', 'addr:house', 'was:amenity',
  'demolished:highway', 'class:bicycle:commute', 'birds_nest', 'codigo',
  'ref:id', 'species:fi', 'wydot_ml_number', 'seismic_resistance',
  'school:trust', 'cycleway:right:width', 'codvia', 'payment:cheque',
  'sez_ele', 'sez_cens', 'removed:highway', 'seamark:light:1:sequence',
  'operator:addr', 'seamark:shoreline_construction:water_level',
  'authentication:none', 'change', 'railway:signal:crossing_distant:form',
  'proposed:lanes', 'min_level', 'occupant:day',
  'railway:signal:crossing_distant', 'cave:ref', 'person:date_of_death',
  'expected_lwn_route_relations', 'highway:cycle', 'floor:material:type',
  'screen', 'image_direction', 'disused:public_transport', 'fountain',
  'ref:lda', 'preschool', 'verge', 'damage:structure', 'earthquake:damage',
  'material:de', 'ref:capad:pa_id', 'track_detail', 'addr:street:ar',
  'province', 'school:language', 'previously', 'check_date:tactile_paving',
  'survey_point:datum_aligned', 'dance:teaching', 'type:haiti',
  'railway:radius', 'excavation', 'comoros-dgsc:code', 'oid', 'contributor',
  'addr:department', 'building:condion', 'church:type',
  'communication:television', 'cadastre:utilization', 'geobase:roadclass',
  'seamark:topmark:colour_pattern', 'seamark:light:2:height', 'toilets:type',
  'note:mk408', 'seamark:bridge:clearance_width', 'railway:switch:resetting',
  'author', 'disused:aeroway', 'recording:automated', 'education',
  'public_bookcase:type', 'position', 'name:bo', 'fire_hydrant:awwa_class',
  'pump:status', 'maxspeed:motorcycle', 'ref:nswgnb', 'lit_by_led',
  'light:power', 'maxweight:hgv:conditional', 'short_name:uk',
  'sidewalk:right:bicycle', 'ramp:luggage', 'name:start_date',
  'dcgis:pubdate', 'extra_curves', 'contact:linkedin', 'duration:backward',
  'fare_zone', 'url:miserend', 'drinking_water:seasonal',
  'napervillegis:prop_id', 'supermarket', 'generator:output:hot_water',
  'napervillegis:loc_id', 'city:left', 'hurricane:damage', 'brp_access',
  'recycling:electrical_appliances', 'bridge:movable', 'piste:ref',
  'ref_codcat', 'fire_hydrant:location', 'oldhousenumber', 'repair',
  'emuia:id', 'place:nswgnb', 'genus:ja', 'drink:wine', 'old_addr:street',
  'nest_mount', 'traffic_signals:arrow', 'gnis:name', 'lda:criteria',
  'name:botanical', 'mineral', 'waterway:category', 'maxweightrating:hgv',
  'ref:hkbus', 'city', 'lfd:criteria', 'seamark:light:2:range',
  'seamark:light:2:sector_start', 'payment:unionpay',
  'seamark:light:2:sector_end', 'bicycle:lanes:forward', 'neighborhood',
  'socket:schuko', 'name:ba', 'ref_int', 'building:type:de',
  'socket:type2_combo:output', 'climbing:rock', 'admin_ref',
  'school:boarding', 'evacuation_route', 'toilet', 'openfire',
  'disused:boundary', 'name:wuu', 'theatre:type', 'building:source',
  'railway:signal:whistle:form', 'name:he1', 'buoy:colour', 'ref:walmart',
  'ref:minsktrans', 'railway:signal:crossing', 'genus:pl',
  'bicycle:lanes:backward', 'geobase:nid', 'platforms', 'gtfs:dataset_id',
  'medical_system:western', 'board:title', 'brand:ur',
  'railway:signal:crossing:form', 'garmin:road_id',
  'seamark:buoy_special_purpose:category', 'operator:fr',
  'railway:signal:whistle', 'payment:none', 'marked_trail',
  'ref:nswlpi:cadid', 'devices', 'artist:wikidata', 'isolation',
  'automatic_door', 'tower:material', 'oneway:flow', 'payment:app',
  'climbing:sport', 'addr:last_update', 'siren:type', 'curb',
  'building:architecture:typology', 'raised', 'connectivity', 'vayla_class',
  'check_date:recycling', 'railway:station_category', 'railway:atb-eg',
  'recycling:small_appliances', 'fire_hazard', 'city:right', 'tree_lined',
  'railway:signal:crossing:states', 'seamark:light:2:period',
  'railway:signal:stop:height', 'atm:network', 'tree', 'bic',
  'mvdgis:cod_varian', 'mvdgis:ordinal', 'contact:whatsapp', 'harbour',
  'verify', 'name:prefix:be', 'parking:condition:left:time_interval',
  'personnel:count', 'give_way', 'electrified:rail', 'fence',
  'tracktype:bing', 'mvdgis:desc_linea', 'culvert', 'baby',
  'internet_access:operator', 'maxgcweight:conditional', 'contact:telegram',
  'is_in:groupement', 'access:lanes:forward', 'mast:type', 'phone:mobile',
  'free_flying:site', 'zoo', 'adfc_hl_net', 'drinking_water:type',
  'nest_platform', 'transit:lanes', 'architect:wikidata', 'cargo',
  'turkey_class', 'post_box:mounting', 'creation',
  'building:facade:material', 'way', 'route:status',
  'building:adjacency:level', 'ruins:building', 'source_url',
  'province:left', 'payment:ep_geldkarte', 'access:lanes:backward',
  'animal_keeping', 'hunting_stand', 'railway:atb-ng',
  'linz:garmin_road_class', 'reviewed', 'railway:signal:electricity:height',
  'damage:date', 'sub_sea', 'highway:owner', 'demolished:power', 'street',
  'official_name:zh', 'is_in:health_level8', 'linz:sufi', 'addr:rt',
  'monitoring:rainfall', 'cycleway:right:traffic_sign', 'display_surface',
  'working_test:date', 'place_of_worship', 'fuel:adblue', 'last_checked',
  'seamark:light:3:colour', 'tower', 'autor', 'drought_prone', 'name:hak',
  'seamark:light:3:character', 'socket:chademo:output', 'inline_skates',
  'check_date:tracktype', 'official_name:ru', 'drink:beer', 'use',
  'short_protection_title', 'nist:state_fips', 'communication:lte',
  'height:median', 'building:roof:levels', 'was:power',
  'seamark:light:3:sector_start', 'seamark:light:3:sector_end',
  'cycleway:left:bicycle', 'crossing:chicane', 'ref:developer',
  'contact:webcam', 'amperage', 'drive_in', 'description2',
  'building:check_date', 'fee:conditional', 'occupant:night',
  'seamark:light:3:height', 'lot', 'bridge_ref', 'source_type',
  'seamark:light:3:range', 'recycling:books', 'abandoned:amenity',
  'artwork_subject', 'benchmark', 'water_point', 'ref:pol_id',
  'socket:typee', 'traffic_sign:4', 'long_name', 'railway:derail',
  'maxspeed:note', 'service:vehicle:oil_change', 'abandoned:landuse',
  'note:maxspeed', 'fuel:octane_87', 'addr:street2', 'disused:admin_level',
  'ref:kmb', 'ref:terna', 'generator:model', 'design:year', 'tobacco',
  'blind', 'wpt_description', 'orig_name', 'ref:deldot', 'language:en',
  'breast', 'seamark:beacon_lateral:colour_pattern', 'lst:area_ha',
  'building:year_built', 'drink:coffee', 'name:wikipedia',
  'motor_vehicle:lanes', 'building:form', 'destinations',
  'wheelchair:description:de', 'max_level', 'official_name:ja',
  'loading_dock', 'parking:lane', 'lst:ref', 'primary_use', 'sub_bacia',
  'seamark:light:3:period', 'name:nds', 'aerodrome:type', 'tee',
  'visual:condition', 'maxstay:conditional', 'repeat_on', 'health',
  'light:aviation', 'depth:source_quality', 'maxspeed:motorcar',
  'cycleway:width', 'resort', 'branch:type', 'fire_hydrant:style',
  'railway:signal:combined:substitute_signal', 'year', 'real_ale',
  'athletics', 'construction_year', 'lock_ref', 'jel', 'addr:street:zh',
  'nudism', 'table', 'occupant:morning', 'destination:colour:forward',
  'name:fur', 'name:ky', 'proposed:building', 'airmark',
  'seamark:buoy_lateral:reflectivity', 'est_height', 'ref:rspo',
  'bicycle_parking:position', 'picnic_table', 'dogs', 'capacity:charging',
  'start_date:railway', 'truck', 'attribution_name', 'recycling:wood',
  'protection_title:en', 'coastal', 'transport', 'detour', 'label',
  'description:ru', 'note:businessname', 'maxspeed:seasonal:winter',
  'copyright', 'bus_routes', 'service:bicycle:rental', 'elevator',
  'network:area', 'building:neighbor', 'maxspeed:sign', 'stream:type',
  'flag', 'name:dsb', 'collection_plate', 'vehicle:lanes',
  'railway_milepost', 'parcel_pickup', 'anglican', 'width:street',
  'voltage-low', 'occupant:evening', 'dual_carriage', 'livestock',
  'traffic_signals:motor_vehicle', 'photo', 'name:en4', 'post:street',
  'service:bicycle:tools', 'addr:side', 'area:ha', 'kvl_hro:desc',
  'addr:street:corner', 'plinthlevel:height', 'pole:type', 'ine:code',
  'check_date:collection_times', 'traffic_signals:ref', 'offshore',
  'survey_point:class', 'gaz2012:ref', 'vacant', 'diet:gluten_free',
  'addr:housenumber2', 'post_office', 'short_name:ru',
  'parking:condition:both:time_interval', 'oneway_type',
  'accessibility_source', 'cycleway:left:surface',
  'parking:condition:right:maxstay', 'lamp:light', 'name:tg',
  'via_ferrata_scale', 'temporary', 'distance:backward', 'gtfs:shape_id',
  'end', 'toll:operator', 'hole:diameter', 'street_lamp', 'sidewalk:width',
  'post:housenumber', 'width:lanes:backward', 'light:model', 'ref:city',
  'width:lanes:forward', 'operator:description', 'place:area_alternate',
  'bus:lanes:backward', 'eea:cdda:parentiso', 'fvst:name', 'parking:zone',
  'ref:isil', 'modifier', 'eea:cdda:sitecode', 'bus:lanes:forward',
  'fuel:biodiesel', 'cxx:code', 'railway:signal_box', 'sby:bldgytype',
  'divider', 'authentication:nfc', 'railway:vacancy_detection',
  'bus_stop:category', 'student:count', 'fuel:gasoline', 'by_night',
  'place:hu', 'note:sanitation', 'consulate', 'generator:location',
  'addr:housename:en', 'building:maintenance:operator', 'cxx:id',
  'building:use:retail', 'maxspeed:goods', 'pond_use', 'fast_food', 'iof',
  'gsm:cellid', 'fire_path', 'lanes:bus:conditional', 'name:bs',
  'fixme:lamp_model', 'ref:msal', 'separated', 'alt_name:sr',
  'check_date:lit', 'species:mp', 'bicycle:backward', 'milestone',
  'wholesale', 'destination:symbol:forward', 'note:access', 'nhd:way_id',
  'removed:amenity', 'piste:priority', 'was:shop', 'ref:udir_nsr',
  'other_use', 'generator:plant', 'disused:political_division',
  'disused:power', 'climbing:trad', 'language:ar',
  'railway:signal:main_repeated', 'nysgissam:nysaddresspointid:1', 'ref:elr',
  'secondary_use', 'maxspeed:bus:backward', 'ref:at:gkz',
  'seamark:light:4:colour', 'destination:colour:backward', 'routing:bicycle',
  'golf:course', 'hov:minimum', 'province:right', 'oneway:bus',
  'seamark:light:4:character', 'operator:guid', 'depth:exposition',
  'vicmap:prims_id', 'vicmap:uid', 'maxspeed:hgv:backward:conditional',
  'stamping_machine', 'maxspeed:trailer:backward', 'spa', 'indoor:level',
  'name:pronunciation', 'oneway:conditional', 'sidewalk:left:bicycle',
  'ksh_ref', 'seamark:light:4:sector_start', 'cycleway:right:foot',
  'surface:note', 'seamark:light:4:sector_end', 'generator:modules',
  'ft_symbol', 'note:project_page', 'name:grc', 'maxspeed:bus:forward',
  'ref:ur', 'ref:boomnummer', 'loc_name:en', 'teryt:terc', 'bike_ride',
  'summit:cross', 'hunting', 'end_date:railway', 'naturbase:verneform',
  'naturbase:url', 'ref:naturvern', 'maxspeed:trailer:forward',
  'drinking_water:legal', 'alt_name:el', 'seamark:light:4:height',
  'disused:landuse', 'stairwell', 'climbing:length',
  'cycleway:right:smoothness', 'addr:hamlet:lld',
  'maxspeed:hgv:forward:conditional', 'demolished', 'guyed', 'police',
  'watsan:type', 'hazard_prone', 'seamark:light:4:range',
  'educamadrid:cod_centro', 'educamadrid:bilingue', 'addr:housename:zh',
  'ncn', 'educamadrid:transporte', 'educamadrid:comedor', 'seamark:status',
  'educamadrid:horario_amp', 'name:adjective',
  'educamadrid:publico_bilingue', 'aerialway:duration', 'died',
  'species:native', 'addr:suite', 'highway:source', 'catastro:ref:street',
  'seamark:light:2:sequence', 'fuel:octane_80', 'crossing:bollard',
  'door:type', 'garmin:road_class', 'recycling:aluminium', 'addr:city:ur',
  'educamadrid:tipo', 'railway:signal:main_repeated:form',
  'destination:country', 'company', 'basement', 'ref:vicmap:pfi',
  'communication:gsm-r', 'light:height', 'farmyard', 'ele:source',
  'educamadrid:numero_portal', 'educamadrid:municipio', 'sms', 'plat',
  'educamadrid:telefono', 'pathtype', 'educamadrid:tipo_via', 'umts:cellid',
  'shoulder:surface', 'destination:colour:text', 'educamadrid:codigo_postal',
  'disused:man_made', 'ref:ibnr', 'passing', 'canvec:source', 'name:lo',
  'motorcycle:conditional', 'old_fhrs:id', 'bicycle:forward', 'ele:bpv',
  'seamark:light:4:period', 'oneway:psv', 'addr:checked', 'ref:lt:kpd',
  'city_limit', 'note:direction', 'seamark:wreck:category', 'ref_code',
  'drain:point_feature', 'monorail', 'destination:symbol:backward',
  'socket:type2:current', 'language:de', 'stilts', 'payment:apple_pay',
  'bgri:code', 'paving_stones:shape', 'source_ref:hgv', 'payment:dkv',
  'shrubbery:density', 'check_date:cycleway', 'contact:viber',
  'road:separated', 'payment:others', 'cycleway:left:width',
  'abandoned:aeroway', 'name_base', 'alternate', 'lat', 'road_shield_color',
  'maxspeed:bus:conditional', 'old_name:1970', 'sidewalk:both:bicycle',
  'name:ast', 'animal_breeding', 'landmark', 'cuisine:ja',
  'educamadrid:nombre_via', 'alt_name:ko', 'historic:electrified',
  'railway:signal:crossing_info:form', 'sac_scale_ref',
  'is_in:neighbourhood', 'oneway:foot', 'name_type', 'moved',
  'suspected:designation', 'ref:sisa_codigo', 'city_id', 'hot_water',
  'fvst:fixme', 'maxspeed:tourist_bus', 'cycleway:buffer',
  'seamark:radar_reflector', 'projet:eboci', 'name:ce',
  'railway:signal:departure', 'railway:signal:departure:form',
  'operational_status:availability', 'int_ref:colour',
  'railway:signal:crossing_info', 'railway:switch:movable_frog',
  'construction:highway', 'addr:place:ar', 'residential:type_idn', 'note:no',
  'village_id', 'canvec:uuid', 'indoormark', 'lot_type',
  'payment:account_cards', 'aerialway:bubble', 'opening_hours:kitchen',
  'ref:dsa', 'bulk_purchase', 'historic:power', 'mp_type',
  'water_tank:street', 'note:source', 'building:adjacency:difference',
  'short_name:sr', 'alt_name:ja', 'postal_code:country', 'ksrg',
  'brand:wikipedia:ur', 'site_ownership', 'facility:nature', 'ref:cui',
  'destination:ref:to:lanes', 'fdot:rci_section',
  'parking:condition:both:vehicles', 'camp_site', 'region_id',
  'pumping_station', 'seamark:light:5:colour', 'climbing:grade:uiaa',
  'description:no', 'aerialway:heating', 'healthcare:speciality:de',
  'cash_withdrawal', 'lte:cellid', 'seamark:light:5:character',
  'addr:city:ps', 'owner:en', 'seamark:light:5:sector_start', 'name:iu',
  'seamark:light:5:sector_end', 'ref:hiking', 'dist:red', 'blocdesc',
  'bridge:name:ja', 'official_name:es', 'pid', 'railway:signal:wrong_road',
  'fenced', 'payment:wire_transfer', 'railway:signal:wrong_road:form',
  'cycleway:bicycle', 'razed:highway', 'flag_skip',
  'it:fvg:regional_catalog:corsi_acqua:nome_foreste',
  'parking:condition:right:default', 'calibration:lon', 'polling_station',
  'addr:city:pnb', 'ref:bldam', 'lamp:tilt', 'addr:city:ks',
  'abandoned:name', 'fallow', 'calibration:lat', 'seamark:light:5:height',
  'dc-gis:pubdate', 'beacon:uuid', 'railway:signal:departure:states', 'vid',
  'bid', 'addr:city:sd', 'vildesc', 'born', 'railway:signal:catenary_mast',
  'maxspeed:plus', 'lanes:psv:backward', 'lanes:bus:forward', 'ref:gsi',
  'flashing_lights', 'ogr_pkid', 'objectid', 'gambling', 'wpt_symbol',
  'payment:uta', 'beacon:minor', 'beacon:major', 'sidewalk:right:width',
  'maxspeed:taxi', 'flood_depth', 'roof:type',
  'parking:condition:left:maxstay', 'mapseg:extra_node', 'flood_latest',
  'level_crossing', 'seamark:beacon_lateral:reflectivity',
  'surface_condition', 'seamark:landmark:conspicuity', 'ref:ztm',
  'seamark:light:5:range', 'railway:signal:crossing_info:caption',
  'waterway:kilometer', 'building:use:office',
  'damage:evaluation_step:imagery', 'county', 'seamark:light:3:sequence',
  'destination:street:to', 'seamark:light:vertical_length',
  'communication:gsm', 'name:mt', 'fixme:wikipedia', 'abandoned:electrified',
  'railway:track_ref:signals', 'len', 'socket:type2:voltage', 'refugee',
  'display:digital', 'int_ref:ar', 'sources', 'ref:cadc:2021',
  'man_made:material', 'sidewalk:right:smoothness', 'int_name:prefix',
  'parking_lane', 'seamark:buoy_lateral:colour_pattern',
  'fi:hkr:kunnossapitoluokka', 'note:highway', 'flood_duration',
  'seamark:light:5:period', 'man_made:colour',
  'railway:signal:station_distant', 'seamark:light:1:group', 'lon',
  'railway:signal:station_distant:form', 'climbing:grade:saxon:min',
  'genus:ar', 'ref:sisa_tipologia', 'animal_keeping:type',
  'seamark:pile:category', 'on_demand', 'salting:operator', 'ref:crs',
  'ref:gobiernu_cw', 'surrey:geodb_oid',
  'seamark:restricted_area:restriction', 'sub_sea:type', 'unsigned',
  'motorway_link:name', 'paved', 'parking:condition:left:vehicles',
  'ref:se:scb', 'bldam:criteria', 'wheelchair:step_height',
  'education_system:ru_standard', 'railway:signal:crossing_info:height',
  'genus:wikipedia', 'golf:par', 'avgspeed', 'council_name',
  'recording:remote', 'route:category', 'info', 'wikipedia:ar',
  'parking:condition:reason', 'change:both_ways', 'id:ctrn_fvg',
  'sidewalk:right:foot', 'service:bicycle:second_hand', 'marine', 'b:type',
  'official_name:fr', 'destination:ref:to:forward', 'water_tank:housenumber',
  'marker:shape', 'service:vehicle:diagnostics',
  'information:public_transport', 'name:nn', 'ref:woonplaatscode', 'ref:ptv',
  'ft_link', 'access:both_ways', 'telescope:type', 'breakfast', 'addr:rw',
  'fhrs:rating', 'motorhome', 'seamark:light:exhibition',
  'seamark:pipeline_submarine:category', 'naturbase:verneplan',
  'left:province', 'ref:svhl', 'proposed:ref', 'lamp:type', 'id_fb',
  'payment:v_pay', 'owner:wikidata', 'count', 'railway:signal:stop:caption',
  'service:vehicle:new_car_sales', 'vegetation', 'munro', 'alt_name:pl',
  'destination:colour:back', 'plant:type', 'speed_pedelec',
  'disused:tourism', 'entrance_marker:subway', 'protection_status', 'mown',
  'right:province', 'long_name:ar', 'alt_int_name', 'seamark:period_start',
  'seamark:period_end', 'addr:type', 'damage:evaluation_date:imagery',
  'overtaking:forward', 'region:left', 'year_built',
  'railway:signal:train_protection:form', 'ref:shop:num', 'plantation',
  'ele:ft', 'disused:leisure', 'ref:dhis2', 'sinkhole', 'owner:zh',
  'railway:signal:distant:shape', 'toll:method', 'construction:building',
  'nuclear_explosion:country', 'railway:historic', 'piste:lanes',
  'nuclear_explosion:site', 'name:ceb', 'version', 'ref:tn:codegeo',
  'addr:street:ru', 'planned:building', 'electric_power',
  'siggra:energy_saving', 'siggra:quality', 'building_count',
  'abandoned:military', 'openplaques:id', 'mitre:colour', 'watsan:location',
  'operator:be', 'sdot:bike_rack:type', 'sdot:bike_rack:facility',
  'opengeodb:lon', 'nuclear_explosion:type', 'sdot:bike_rack:id',
  'opengeodb:lat', 'old_name:pl', 'sdot:bike_rack:condition',
  'building:levels:aboveground', 'seamark:daymark:shape',
  'uk_postcode_centroid', 'parking:condition:right:vehicles',
  'mineshaft_type', 'addr', 'railway:signal:train_protection',
  'nid:inscription_date', 'destination:ref:to:backward',
  'access:lanes:both_ways', 'commune', 'ref:idol', 'xmas:feature',
  'headframe', 'seamark:beacon_special_purpose:colour_pattern',
  'ref:pat:cat', 'water_slide', 'name:prefix:at', 'parking:ticket:zone',
  'ref:pat:id', 'abandoned:gauge', 'nuclear_explosion:date:utc',
  'note:retag', 'service:vehicle:used_car_sales', 'cost', 'street:id',
  'ladder', 'survey:lon', 'survey:lat', 'language:fr', 'lanes:unmarked',
  'is_in:region_code', 'watsan:users_per_day', 'road_name', 'survey:datum',
  'sector:name', 'pump:style', 'calibration:datum', 'survey:ele',
  'historic:operator', 'is_in:province_code', 'educamadrid:fax',
  'indoor_seating', 'maxweightrating:hgv:conditional', 'highway:position',
  'boundary_name', 'ref:seedcode', 'impromptu', 'mdt_base_route',
  'operator:ownership', 'nuclear_explosion:shot_name:en',
  'nuclear_explosion:series', 'shelterid', 'villageid', 'crane:mobile',
  'plotdesc', 'network:ja', 'seamark:notice:2:function', 'training',
  'seamark:notice:1:function', 'alt_name:es', 'loc_name:prefix',
  'is_in:department', 'seamark:notice:2:category',
  'seamark:notice:1:category', 'is_in:admin_level7', 'name:an',
  'facility_type', 'column:size', 'nuclear_explosion:purpose', 'landscape',
  'physically_present', 'flood:rain', 'closest_town', 'loc_name:fr',
  'memorial:subject', 'last_renovation', 'seamark:mooring:water_level',
  'block', 'usability:skate', 'portable', 'seamark:light:4:sequence',
  'volcano:status', 'grade', 'crossing:surface', 'endpoint:busbar', 'rock',
  'scooter', 'image:0', 'addr:sector', 'school:trust:name', 'legal',
  'jastrzebiegis:opis', 'note:fr', 'seamark:daymark:colour',
  'lanes:psv:forward', 'storage', 'school:specialty', 'group_only',
  'speisebezirk', 'psv:lanes:backward', 'service:vehicle:inspection',
  'oa:version', 'oa:lon', 'oa:lat', 'light', 'lit:indirect',
  'project:anr_cohesion_bouake', 'sidewalk:left:width', 'oa:imported_by',
  'memorial:ref', 'community', 'communication:mobile',
  'seamark:obstruction:category', 'quality', 'earth_bank', 'text_colour',
  'overtaking:backward', 'loc_name:ca', 'destroyed:highway', 'species:ru',
  'cafe', 'description:sk', 'note:sk', 'outdoor',
  'nuclear_explosion:time:utc', 'payment:nfc', 'lawyer',
  'seamark:light:6:colour', 'name:language', 'meadow_type', 'notional_area',
  'cash_withdrawal:type', 'railway:signal:traversable:type',
  'not:brand:wikidata', 'ski:nordic', 'kct_green',
  'seamark:light:6:character', 'contact:addr', 'trafikverket', 'trailer',
  'floor', 'seamark:light:6:sector_start', 'fields', 'nature',
  'disused:addr:housenumber', 'cash_withdrawal:fee', 'name:mrj',
  'seamark:light:6:sector_end', 'language:others', 'nrhp:inscription_date',
  'railway:signal:main_repeated:states', 'brand:ko',
  'heritage:operator:short', 'school:enrolment', 'vaccination',
  'boundary_type', 'permanent', 'type_idn', 'insurance',
  'vine_row_orientation', 'shooting', 'long_name:fr', 'levelpart',
  'building:buildyear', 'name:km', 'turning_circle', 'copy_facility',
  'motorway', 'seamark:light:6:height', 'tunnel:name:en', 'clcfile',
  'protection_object', 'permanent_camping',
  'cash_withdrawal:purchase_required', 'branch:en', 'shared_taxi',
  'architect:wikipedia', 'place:ro', 'seamark:light:6:range',
  'psv:lanes:forward', 'building:roof:height',
  'seamark:marine_farm:category', 'school:trust:type', 'pe:ubigeo',
  'message:reverse', 'destination:ref:lanes:forward', 'park_type',
  'is_in:health_level10', 'is_in:right', 'census', 'cmt', 'name:arc',
  'contact_person', 'ref:whc', 'wikipedia:pl', 'payment:google_pay',
  'deep_draft', 'name:is', 'legal_status', 'repd:id', 'water:type',
  'brand:pa', 'left:county', 'ref:fr', 'seamark:cable_submarine:category',
  'right:county', 'ethnic', 'parking:condition:both:maxstay',
  'seamark:light:6:period', 'ref:nobil', 'railway:end_date',
  'seamark:light:2:category', 'dist:white', 'seamark:light:1:category',
  'building:levels:top', 'building:demolished', 'service:vehicle:brakes',
  'crossing:on_demand', 'whitewater:section_grade', 'railway:freight',
  'area:aeroway', 'restriction:bicycle', 'shoulder:line', 'lit:perceived',
  'is_in:left', 'bath:type', 'lst:tillkomst', 'roadid', 'atm:operator',
  'cycleway:left:foot', 'was:landuse', 'species_ja', 'school:de',
  'metcouncil:node_id', 'sidewalk:left:smoothness', 'crossing:width',
  'marking', 'crossing:end', 'awareness:red_cross', 'emergency:both_ways',
  'historic:usage', 'pipeline:ref', 'place_numbers', 'beacon:frequency',
  'mvdgis:nro_espaci', 'parking:condition:left:default', 'population:2015',
  'crown_radius', 'solar:tracking', 'ref_old', 'abandoned:ref',
  'fence:function', 'railway:signal:route', 'change_machine',
  'socket:type2_cable', 'end_date:source', 'destroyed:building:levels',
  'ref:regon', 'cycleway:both:segregated', 'abandoned_date',
  'placement:both_ways', 'railway:signal:route:form', 'guide_type',
  'bus_lines', 'memorial:addr:city', 'parking:condition:both:residents',
  'class', 'memorial:addr:street', 'railway:signal:whistle:only_transit',
  'stop_code', 'ref:section', 'ctry', 'ref:edubase:group',
  'destination:int_ref:lanes', 'seamark:light:5:sequence',
  'kystverket:information', 'car_wash', 'name:si', 'wdb:source',
  'taxon:genus', 'parking:condition:both:default', 'tree:type',
  'building:prefabricated', 'building:number', 'garmin-type',
  'bridge_number', 'dist:blue', 'new', 'telegram', 'parish_type', 'corbett',
  'razed', 'kerb:right', 'seamark:landmark:function', 'gis-lab:status',
  'heritage:ref:inspire', 'gate', 'ele:local', 'heritage:ref:gem',
  'name:scn', 'was:natural', 'telephone', 'buskerudbyen:cycleway',
  'brand:th', 'gas_insulated', 'destination:colour:ref', 'message:front',
  'seamark:pipeline_submarine:product', 'nuclear_explosion:yield',
  'seamark:recommended_track:orientation', 'overtaking:trailer:conditional',
  'es_fid', 'ref:fa', 'turn:forward', 'kerb:left', 'addr:postal_district',
  'educamadrid:url', 'nrhp:criteria', 'railway:signal:train_protection:type',
  'scale', 'fire_station:type', 'monitoring:cosmic_ray', 'ccc',
  'addr:old_street', 'forested', 'routeparam', 'meadlsc_description',
  'ref:seq', 'ref:dpti:suburb_num',
  'it:fvg:regional_catalog:corsi_acqua:nome_consorzio', 'gtfs:id',
  'destination:to:lanes', 'note:fi', 'socket:type2_cable:output',
  'addr:street_direction_prefix', 'education_profile:general',
  'communication:umts', 'addrcountry', 'whc:inscription_date', 'name:wa',
  'construction:surface', 'name:lld', 'ref:ipa', 'building:shape',
  'seamark:mooring:colour', 'service:tipping', 'aerialway:station',
  'operation', 'alt_name:ur', 'flickr', 'label:manufacturer', 'ohv',
  'disused:military', 'beacon:code', 'post:postcode', 'diet:meat',
  'surface:de', 'maxspeed:default', 'education:type', 'road_lcd', 'name:syc',
  'stop_name', 'jastrzebiegis:id', 'topmark', 'width:carriageway',
  'seamark:notice:distance_down', 'post_box:apertures',
  'seamark:mooring:shape', 'kind', 'stone_type', 'routes', 'species:ca',
  'seamark:notice:distance_up', 'pitlatrine:description', 'ref:usfs',
  'condo', 'pilgrimage', 'graham', 'turn:backward', 'place_of_worship:type',
  'railway:line_ref', 'railway:maximum_current', 'ref:ctb',
  'deposit_occurrence', 'motorcycle:lanes', 'destination:ref:lanes:backward',
  'wrong_sign', 'railway:platform_height', 'railway:gauge',
  'postal_code:serial', 'parking:condition:left:reason', 'gantry:type',
  'poles', 'historic:highway', 'aeroway:light', 'pseudo',
  'railway:platform_length', 'service:vehicle:repairs', 'name:ee',
  'removed:operator', 'certifications', 'old_name:fr',
  'seamark:notice:2:impact', 'sym', 'cyclerating', 'seamark:notice:1:impact',
  'desert', 'fungsi_bgn', 'ref:norgesgruppen', 'service:vehicle:car_parts',
  'fdot:county', 'seamark:light:2:group', 'guideposted_leads_to_ref',
  'post:city', 'road', 'name:mg', 'parking:condition:area', 'kerb:both',
  'building:roof:material', 'park:type', 'lanes:bus:backward',
  'parking:condition:both:reason', 'disused:route', 'courts', 'request_stop',
  'suburb', 'toll:2021-08-31', 'parking:condition:right:residents', 'ruined',
  'wikipedia:sl', 'arivac:name', 'massage', 'arivac:type_id',
  'cyclestreets_id', 'building:owner', 'description:pl', 'operational',
  'school_type', 'rank', 'seamark:bridge:clearance_height_closed',
  'parish:wikidata', 'sign', 'parish:wikipedia', 'reference:feature',
  'profile', 'safety:mask:covid19', 'changing_table:location',
  'destination:en', 'class:bicycle:roadcycling', 'ref:se:pts:postort',
  'submerged', 'operator:funding', 'connection_point', 'safety_rope', 'dock',
  'railway:etcs:start_date', 'number', 'milepost:county',
  'routing:motor_vehicle', 'recycling:cooking_oil', 'osmuid',
  'description:he', 'nod1', 'historic:start_date', 'nod2', 'gender_access',
  'abandoned:waterway', 'generator:output:biogas', 'highway:note',
  'nuclear_explosion:hole', 'name:udm', 'fire_object:type', 'households',
  'origin', 'toll:hov', 'sidewalk:right:traffic_sign',
  'check_date:existence', 'shoulder:smoothness', 'ref:yamato:area4disaster',
  'ref:yamato:subarea4disaster', 'arivac:typetxt',
  'seamark:light:1:national_information', 'scrub', 'name:smj',
  'intersection', 'note:warning', 'maintained', 'lottery', 'power_source',
  'lunch', 'water_type', 'heritage:website:sipa', 'src:id', 'ref:fiskeridir',
  'university', 'de:strassenschluessel_exists', 'nswlpi:cadid',
  'demolished:building:levels', 'unosat:objectid', 'unosat:acquisition_date',
  'waste_basket:excrement_bags', 'heritage:operator:wikidata',
  'unosat:event_code', 'ref:posten', 'cycleway:left:traffic_sign',
  'note:toll', 'twitter', 'unnamed', 'name:gu', 'thermometer', 'ref:volan',
  'barrier:keypad', 'alcohol', 'last_check', 'bridge:name:ko',
  'short_name:ar', 'piste:trailblazed', 'parking:condition:right:reason',
  'is_in:block', 'dsa:criteria', 'route_version', 'minibus',
  'kitchen:facilities', 'railway:name', 'destination:symbol:to',
  'bus_stop:type', 'period', 'fhrs:inspectiondate', 'post:state',
  'redwood_city_ca:bldg_id', 'description:hu', 'cycleway:smoothness',
  'bath:open_air', 'cosmha_stm', 'recycling:garden_waste',
  'cycleway:segregated', 'socket:type1', 'plant:output:hot_water',
  'construction:program', 'wheelchair:description:cs', 'climbing:bolted',
  'railway:signal:route:states', 'traffic_restriction', 'fixing_phase',
  'piste:status', 'seamark:light:2:national_information', 'compensator',
  'community:gender', 'contact:country', 'landslide_prone', 'marilyn',
  'historic:ref', 'ref:park', 'alt_name:uk', 'service:vehicle:body_repair',
  'seamark:light:3:national_information', 'hour_on', 'is_in:admin_level8',
  'hour_off', 'water_system', 'overtaking:motor_vehicle', 'name:gv',
  'nagacity:surf_type', 'nagacity:rdbuffer', 'nagacity:cond_id',
  'nagacity:categ_id', 'drain', 'name:or', 'note:time', 'caravan',
  'fuel:electricity', 'was:operator', 'ref:catastro',
  'destination:street:lanes', 'seamark:signal_station_traffic:category',
  'payment:mastercard_contactless', 'genus:lv', 'class:bicycle:touring',
  'genus:uk', 'water_tank:city', 'sidewalk_orientation',
  'tram:segregation:physical', 'seamark:radio_station:category',
  'fuel:biogas', 'ponderado', 'nivel_ts', 'vulnerab_r', 'hombre', 'mujer',
  'cat_resist', 'riesgo_rm', 'riesgo_ts', 'riesgo_bf', 'riesgo_ca', 'cat_3',
  'vulnerab', 'historic:end_date', 'nivel_rm', 'nivel_bf', 'nivel_ca',
  'tot_viv', 'tot_hab', 'porc_c1', 'porc_c2', 'porc_c3',
  'winter_service:priority', 'alt_name_3', 'quartier',
  'nuclear_explosion:height_of_burst', 'vhf', 'proposed:maxspeed',
  'payment:troika', 'not:addr:postcode', 'parking:primary_usage', 'ele:nn',
  'area:size:ha', 'established', 'variable_message:model', 'kll:oid',
  'historic:building', 'is_in:ward', 'course', 'name:sc', 'artist:wikipedia',
  'classification', 'origen', 'cycleway:right:buffer', 'weather:anemometer',
  'cycleway:left:smoothness', 'payment:ep_easywallet', 'old_shop',
  'checkpoint:type', 'was:railway', 'depot', 'disused:operator', 'cabins',
  'addr:city:es', 'feeding:type', 'piste:classic:lanes', 'capacity:note',
  'railway:signal:electricity:turn_direction',
  'payment:mastercard_electronic', 'laundry_service', 'guidepost:lastcheck',
  'active_traffic_management', 'maxheight:physical', 'wikipedia:es',
  'ele:wgs84', 'lcn_type', 'socket:schuko:output', 'glacier:type',
  'seamark:light:6:sequence', 'dist:yellow', 'taxon:ru', 'payment:bancomat',
  'seamark:platform:category', 'drain:material',
  'seamark:light:4:national_information', 'obstacle_name', 'name:vls',
  'payment:blik', 'official_name:ar', 'watsan:water_availability',
  'memorial:conflict', 'aerodrome', 'demolished:amenity', 'unit',
  'operator:de', 'kct_yellow', 'feeding:for', 'vicinal_type',
  'ref:us:ny:swis', 'payment:alipay', 'farmland:type_idn', 'operator:ref',
  'capacity:hgv', 'kod', 'pedestrian', 'certification', 'abandoned:usage',
  'is_in:taluk', 'separation:right', 'flood:send', 'memorial:name',
  'name:etymology:wikidata:missing', 'old_name:lt', 'sidewalk:left:foot',
  'payment:prepaid_ticket', 'name:gr', 'surface:middle', 'toilets:female',
  'historic:era', 'governance', 'haifa-ref', 'castle_type:de',
  'elementary_school_district', 'payment:paypal', 'fair_trade',
  'sanitary_dump_station:chemical_toilet', 'toilets:male',
  'sanitary_dump_station:grey_water', 'rcn_region', 'source_ref:lanes',
  'red_turn:right', 'recycling:electrical_items', 'brand:official_name',
  'separation:left', 'seamark:light:3:group', 'ground_floor:height',
  'aeroway:light:colour', 'toll_method', 'seamark:light:7:character',
  'ruian_id', 'addr:street:ca', 'aeroway:light:character',
  'disability_access', 'seamark:light:7:colour', 'payment', 'milestone_type',
  'phone:call_center', 'defibrillator:location:en', 'flag:colour',
  'design:note', 'mattress', 'physical', 'name:zgh',
  'entrance_marker:s-train', 'historic:amenity', 'planned', 'name:historic',
  'ref:mav', 'water_source:id', 'official', 'highway:-1986', 'indoor:area',
  'routing:entrance', 'old_name:zh', 'old_name:es', 'brand:el',
  'brand:wikipedia:pa', 'qroti:place_id', 'seamark:light:7:sector_start',
  'seamark:light:7:height', 'commercial', 'seamark:light:7:sector_end',
  'name:sh', 'snowshoe', 'pipe_type', 'communication:bos',
  'construction:amenity', 'interval:conditional', 'removed:ref', 'heating',
  'payment:wechat', 'cocktails', 'note:gtfs', 'recycling:metal',
  'goods:conditional', 'kind:ru', 'millennium:ref', 'species:sk',
  'operator:phone', 'seamark:light:7:range', 'books',
  'ref:hvakostertannlegen', 'collection', 'teryt:name', 'millennium:date',
  'qroti:mode', 'service:bicycle:chain_tool', 'service:bicycle:diy',
  'is_in:quarter', 'uuid', 'place:village', 'admin_centre:postal_code',
  'pressure', 'drain:profile_open', 'addr:pak', 'fire_hydrant:name',
  'qroti:mode_name', 'tickets:public_transport', 'lst:url', 'beacon',
  'seamark:light:5:national_information', 'maxgcweightrating:hgv',
  'coastline:survey_quality', 'pump_type', 'activity', 'radius',
  'route_marker', 'parking:lane:right:perpendicular', 'housesuffix',
  'note:maxspeed:url', 'seamark:light:7:period', 'biergarten',
  'motorcycle:repair', 'comment:it', 'lettable_surface_area',
  'garmin-roadid', 'climbing:boulder', 'rail', 'itinerary', 'baseball',
  'fire_hydrant_type:yamato', 'volcano:type', 'healthcare:service',
  'ref:nhn', 'monitoring:air_quality', 'side_road', 'name:bat-smg',
  'have_riverbank', 'destination:symbol:lanes:forward', 'from:en',
  'old_name:hu', 'to:en', 'units', 'building:architect', 'ref:gkz',
  'watsan:connection', 'permissive_left_turn', 'status:ru', 'qroti:url',
  'antenna:type', 'amenity:historic', 'educamadrid:distrito',
  'motorroad:tunnel', 'education_level:primary', 'qroti:surveyed', 'arete',
  'bridge_name', 'entrance_marker:train', 'climbing:quality',
  'weather_protection', 'bay', 'nursery', 'vehicle:lanes:forward',
  'parking:condition:left:residents', 'sidewalk:both:width',
  'seamark:signal_station_warning:category', 'grape_variety',
  'staff_count:doctors', 'tfl:programme', 'damage_status', 'camp',
  'operator:it', 'name:prefix:bg', 'traffic_island', 'obstacle:wheelchair',
  'charging_station:output', 'official_route', 'layby', 'ma',
  'railway:signal:speed_limit:deactivated', 'site_status', 'recording',
  'feeding:fodder', 'historic:name', 'name:en5', 'staff_count:nurses',
  'lamp_mount_type:de', 'historic:owner', 'wb_pb:id', 'flucsdesc',
  'uncontrolled', 'mobility:station_id', 'cycleway:oneway', 'ele:msl',
  'traffic_signals:minimap', 'fluccscode', 'parts', 'education:gender_type',
  'piste:grooming:classic:lanes', 'emergency_service', 'payment:bitcoincash',
  'cliff', 'prov', 'alt_name:sv', 'nuclear_explosion:ground_zero_altitude',
  'education:students', 'alt_name:cs', 'paving_stones:pattern',
  'population:source', 'kml_folder', 'contact:yelp',
  'railway:signal:crossing:repeated', 'addr:alt_street', 'note:surface',
  'energy_class', 'railway:signal:main:deactivated', 'animal_shelter',
  'addr:paloaltoca_id', 'drain:profile_covered', 'id:uuid', 'date:converted',
  'name:cadastre', 'accessibility', 'refitted', 'residental',
  'building:irregularity:type', 'lgbtq', 'carpool', 'name:crh', 'fuel:1_50',
  'parking:lane:left:perpendicular', 'note:2',
  'sanitary_dump_station:round_drain', 'lcd', 'area_lcd', 'entrance:steps',
  'roof:ridge:direction', 'building:name', 'whc:criteria', 'hut',
  'animal_boarding', 'water_characteristic',
  'destination:symbol:lanes:backward', 'ref:RS:kucni_broj',
};
