import 'package:every_door/helpers/tags/main_key.dart';

const kTagEmoji = <String, String>{
  'amenity=arts_centre': '🎨',
  'amenity=atm': '🏧',
  'amenity=bank': '🏦',
  'amenity=bar': '🍻',
  'amenity=bench': '🪑',
  'amenity=bicycle_rental': '🚲',
  'amenity=biergarten': '🍻',
  'amenity=bureau_de_change': '💱',
  'amenity=bus_station': '🚏',
  'amenity=cafe': '☕',
  'amenity=casino': '🎰',
  'amenity=cinema': '📽️',
  'amenity=clinic': '🩺',
  'amenity=courthouse': '⚖️',
  'amenity=dentist': '🦷',
  'amenity=doctors': '🩺',
  'amenity=driving_school': '🚗',
  'amenity=fast_food': '🍔',
  'amenity=fire_station': '🚒',
  'amenity=fuel': '⛽',
  'amenity=gambling': '🎰',
  'amenity=hospital': '🏥',
  'amenity=ice_cream': '🍨',
  'amenity=kindergarten': '🧸',
  'amenity=library': '📖',
  'amenity=mobile_library': '📖',
  'amenity=music_school': '🎵',
  'amenity=nightclub': '🕺',
  'amenity=parcel_locker': '📦',
  'amenity=pharmacy': '💊',
  'amenity=place_of_worship': '⛪',
  'amenity=police': '🚓',
  'amenity=post_box': '✉️',
  'amenity=post_office': '📯',
  'amenity=pub': '🍻',
  'amenity=recycling': '♻️',
  'amenity=restaurant': '🍴',
  'amenity=school': '📚',
  'amenity=theatre': '🎭',
  'amenity=toilets': '🚻',
  'amenity=townhall': '🏛️',
  'amenity=university': '🎓',
  'amenity=waste_basket': '🗑️',
  'amenity=waste_disposal': '♻️',

  'shop=alcohol': '🍷',
  'shop=art': '🖼️',
  'shop=baby_goods': '🍼',
  'shop=bag': '👜',
  'shop=bakery': '🥨',
  'shop=beauty': '💅',
  'shop=bed': '🛏️',
  'shop=bicycle': '🚲',
  'shop=books': '📚',
  'shop=butcher': '🥩',
  'shop=car': '🚗',
  'shop=car_parts': '🚗',
  'shop=car_repair': '🚗',
  'shop=chocolate': '🍫',
  'shop=clothes': '👚',
  'shop=coffee': '☕️',
  'shop=computer': '🖥️',
  'shop=confectionery': '🍬',
  'shop=convenience': '🛒',
  'shop=copyshop': '🖨️',
  'shop=cosmetics': '💄',
  'shop=electronics': '📷',
  'shop=equestrian': '🏇',
  'shop=fashion_accessories': '📿',
  'shop=florist': '💐',
  'shop=funeral_directors': '⚰️',
  'shop=furniture': '🛋️',
  'shop=games': '🎲',
  'shop=gift': '🎁',
  'shop=glaziery': '🪟',
  'shop=greengrocer': '🥦',
  'shop=hairdresser': '💈',
  'shop=hearing_aids': '🦻',
  'shop=hifi': '📻',
  'shop=ice_cream': '🍨',
  'shop=jewelry': '💎',
  'shop=kiosk': '🏪',
  'shop=mall': '🛍️',
  'shop=mobile_phone': '📱',
  'shop=motorcycle': '🏍️',
  'shop=motorcycle_repair': '🏍️',
  'shop=music': '🎵',
  'shop=optician': '👓',
  'shop=pastry': '🍰',
  'shop=pet': '🐈',
  'shop=photo': '📷',
  'shop=radiotechnics': '📻',
  'shop=shoe_repair': '👞',
  'shop=shoes': '👞',
  'shop=sports': '⚽',
  'shop=stationery': '✏️',
  'shop=supermarket': '🛒',
  'shop=tailor': '👚',
  'shop=tobacco': '🚬',
  'shop=toys': '🧸',
  'shop=travel_agency': '🧳',
  'shop=vacant': '🚫',
  'shop=video_games': '🎮',
  'shop=watches': '⌚️',
  'shop=wine': '🍷',

  'craft=carpenter': '🛋️',
  'craft=electronics_repair': '🔌',
  'craft=jeweller': '💎',
  'craft=joiner': '🛋️',
  'craft=key_cutter': '🔑',
  'craft=locksmith': '🔑',
  'craft=painter': '🖌️',
  'craft=photographer': '📷',
  'craft=shoemaker': '👞',
  'craft=watchmaker': '⌚️',

  'tourism=attraction': '📸',
  'tourism=gallery': '🖼️',
  'tourism=guest_house': '🏡',
  'tourism=hostel': '🛏️',
  'tourism=hotel': '🏨',
  'tourism=information': 'ℹ️',
  'tourism=motel': '🛏️',
  'tourism=museum': '🏛️',
  'tourism=zoo': '🐘',

  'leisure=adult_gaming_centre': '🎰',
  'leisure=amusement_arcade': '🎮',
  'leisure=dance': '💃',
  'leisure=playground': '🪜',
  'leisure=sports_centre': '⚽',
  'leisure=stadium': '🏟️',

  'office=estate_agent': '🏠',
  'office=government': '🏛️',
  'office=it': '🖥️',
  'office=lawyer': '⚖️',
  'office=surveyor': '🗺️',
  'office=university': '🎓',

  'healthcare=blood_donation': '🩸',
  'healthcare=dentist': '🦷',

  'club=sport': '⚽',
};

String? getEmojiForTags(Map<String, String> tags) {
  final List<String> emoji = [];
  final mainKey = getMainKey(tags);
  if (mainKey != null) {
    final kv = kTagEmoji['${clearPrefix(mainKey)}=${tags[mainKey]}'];
    if (kv != null && kv.isNotEmpty)
      emoji.add(kv);
  }
  tags.forEach((key, value) {
    var kv = kTagEmoji['$key=$value'];
    if (kv != null && kv.isNotEmpty) {
      if (!emoji.contains(kv)) emoji.add(kv);
    }
  });
  return emoji.isEmpty ? null : emoji.join();
}
